### ISSUE TITLE
Resuming a BADS run

### ISSUE THREAD

**Issue by pfebrer** [acerbilab/pybads#41]
Hi, I'm testing your package and it seems to be working amazingly for my use case :)

However, I have two questions regarding how BADS can be initialized:
1. If a previous BADS run has stopped for some reason, is there a way to continue it from that point?
2. More generally, if I have a known set of points of the function to optimize, is there some way I can feed them into BADS, maybe as initial points?

Thanks!

**Comment by lacerbi** [comment]
Thanks for the question - I answered it under our **Discussions** here: https://github.com/orgs/acerbilab/discussions/5

We keep the Issues section of individual repos for actual bugs and developer notes; we use the lab Discussions forum for Q&A since they often apply to multiple versions of our packages (for example this question applies to both the MATLAB and Python versions).
